---
title: "CodeBook"
author: "Hongyan Kang"
date: "March 30, 2017"
output: html_document
---

CodeBook

This is a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data.

The data source

Original data: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
Original description of the dataset: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones
Data Set Information

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

The data

The dataset includes the following files:

'README.txt'

'features_info.txt': Shows information about the variables used on the feature vector.

'features.txt': List of all features.

'activity_labels.txt': Links the class labels with their activity name.

'train/X_train.txt': Training set.

'train/y_train.txt': Training labels.

'test/X_test.txt': Test set.

'test/y_test.txt': Test labels.

```{r}
setwd("C:\\Users\\vince\\Desktop\\Coursera\\Getting and Cleaning Data")

# Get the data
# Download and unzip the dataset from UCI webset
URL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(URL, destfile = "HARDataset.zip", method = "curl")
unzip(zipfile = "HARDataset.zip")

filepath <- file.path("./", "UCI HAR Dataset")
files <- list.files(filepath, recursive = TRUE)
files

# Read data from the files
# Read the Activity files
datActivityTrain <- read.table(file.path(filepath, "train", "Y_train.txt"),header = FALSE)
datActivityTest  <- read.table(file.path(filepath, "test" , "Y_test.txt" ),header = FALSE)
# Read the Subject files
datSubjectTrain <- read.table(file.path(filepath, "train", "Subject_train.txt"),header = FALSE)
datSubjectTest  <- read.table(file.path(filepath, "test" , "Subject_test.txt" ),header = FALSE)
# Read the Feature files 
datFeatureTrain <- read.table(file.path(filepath, "train", "X_train.txt"),header = FALSE)
datFeatureTest  <- read.table(file.path(filepath, "test" , "X_test.txt" ),header = FALSE)

str(datActivityTest)
str(datActivityTrain)

# 1. Merges the training and the test sets to create one data set
# (1) Concatenate the data tables by rows
datActivity <- rbind(datActivityTrain, datActivityTest)
datSubject <- rbind(datSubjectTrain, datSubjectTest)
datFeature <- rbind(datFeatureTrain, datFeatureTest)
# (2) Set names to the variables
names(datActivity) <- c("Activity")
names(datSubject) <- c("Subject")
datFeatureNames <- read.table(file.path(filepath, "features.txt"), header = FALSE)
names(datFeature) <- datFeatureNames$V2
# (3) Merge all data
Finaldata <- cbind(datActivity, datSubject, datFeature)
str(Finaldata)

# 2. Extracts only the measurements on the mean and standard deviation for each measurement
# select names of features with mean() or std()
subsetFeatureNames <- datFeatureNames$V2[grep("mean\\(\\)|std\\(\\)", datFeatureNames$V2)]
# add "Activity" and "Subject" to the selectednames
selectedNames <- union(c("Activity", "Subject"), subsetFeatureNames)
# subset the final table under the mean and std condition
Finaldata2 <- subset(Finaldata, select = selectedNames)
str(Finaldata2)

# 3. Uses descriptive activity names to name the activities in the data set
# read tables from activity_labels
activityLabels <- read.table(file.path(filepath, "activity_labels.txt"),header = FALSE)
# factorize Variale activity in the data frame Data using descriptive activity names
Finaldata2$Activity <- factor(Finaldata2$Activity, labels = activityLabels$V2)
head(Finaldata2, 2)

# 4. Appropriately labels the data set with descriptive variable names.
# prefix t is replaced by time
# Acc is replaced by Accelerometer
# Gyro is replaced by Gyroscope
# prefix f is replaced by frequency
# Mag is replaced by Magnitude
# BodyBody is replaced by Body
names(Finaldata2) <- gsub("^t", "time", names(Finaldata2))
names(Finaldata2)<-gsub("^f", "frequency", names(Finaldata2))
names(Finaldata2)<-gsub("Acc", "Accelerometer", names(Finaldata2))
names(Finaldata2)<-gsub("Gyro", "Gyroscope", names(Finaldata2))
names(Finaldata2)<-gsub("Mag", "Magnitude", names(Finaldata2))
names(Finaldata2)<-gsub("BodyBody", "Body", names(Finaldata2))
# check
names(Finaldata2)

# 5. From the data set in step 4, creates a second, independent tidy data set 
#    with the average of each variable for each activity and each subject.
library(plyr)
Dataset2 <- aggregate(. ~ Subject + Activity, Finaldata2, mean)
Dataset2 <- Dataset2[order(Dataset2$Subject, Dataset2$Activity),]
write.table(Dataset2, file = "tidydata.txt",row.name=FALSE)

# produce codebook 
library(memisc)
codebook(Dataset2)
Write(codebook(Dataset2), file="Data-codebook.txt")
```


The following files are available for the train and test data. Their descriptions are equivalent.

'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.

'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis.

'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration.

'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second.

Transformation details

There are 5 parts:

Merges the training and the test sets to create one data set.
Extracts only the measurements on the mean and standard deviation for each measurement.
Uses descriptive activity names to name the activities in the data set
Appropriately labels the data set with descriptive activity names.
Creates a second, independent tidy data set with the average of each variable for each activity and each subject.
How run_analysis.R implements the above steps:

Require reshapre2 and data.table librareis.
Load both test and train data
Load the features and activity labels.
Extract the mean and standard deviation column names and data.
Process the data. There are two parts processing test and train data respectively.
Merge data set.



